#pragma once
// #define GREETING_TPC "/HOME_AUTOMATION/GREETING"
// #define MOTION_SENSOR_STATE_TPC "MotionSensors/Hall"
// #define DEVICE_OPERATION_CONTROL_TPC "Devices/Operation/Control"
// #define DEVICE_OPERATION_MODE_TPC "Devices/Operation/Mode"
/////#define MOTION_SENSOR_ID "HALL_SENSOR_TABLE_1"
/////#define RELAY_HIGH 0

/////#define MAX_ON_OPERATION_MODE_DURATION_MS 60000

//#define GREETING_TPC "/HOME_AUTOMATION/GREETING"

//#define AUTHORIZATION_REQUESTS_TPC "/HOME_AUTOMATION/AUTHORIZATION_REQUESTS"
//#define AUTHORIZATION_REQUESTS_STATUS_TPC "/HOME_AUTOMATION/AUTHORIZATION_REQUESTS_STATUS"

//#define DEVICE_SETTINGS_REQUEST_TPC "/HOME_AUTOMATION/DEVICE_SETTINGS_REQUEST"
//#define DEVICE_SETTINGS_APPLY_TPC "/HOME_AUTOMATION/DEVICE_SETTINGS_APPLY"

#define BASE_LOCATION_TPC "/HOME_AUTOMATION/HALL"

#define MOTION_TPC "/HOME_AUTOMATION/HALL/MOTION"
#define ILLUMINATION_TPC "/HOME_AUTOMATION/HALL/ILLUMINATION"

// PERIODS
#define PERIOD_ILLUMINATION_READ 10     // seconds
#define PERIOD_MQTT_KEEPALIVE 10        // milliseconds

#define DEVICE_ID "MSH"


